// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHSJ5NNXT665trCpLkAEGNalN8lkVLKnc',
    appId: '1:226229250123:web:b97f423b67efee0b1b45ce',
    messagingSenderId: '226229250123',
    projectId: 'tugasmandiri-jovan',
    authDomain: 'tugasmandiri-jovan.firebaseapp.com',
    storageBucket: 'tugasmandiri-jovan.firebasestorage.app',
    databaseURL: 'https://tugasmandiri-jovan-default-rtdb.firebaseio.com',
    measurementId: 'G-V3FDRDHGDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTosudyJsCsM2yCUWHj0QJWvRrzKk9aQ',
    appId: '1:226229250123:android:8411097366d34dad1b45ce',
    messagingSenderId: '226229250123',
    projectId: 'tugasmandiri-jovan',
    databaseURL: 'https://tugasmandiri-jovan-default-rtdb.firebaseio.com',
    storageBucket: 'tugasmandiri-jovan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVEtaTuxkPKzq9cql_jZSCfbD-AXj33yc',
    appId: '1:226229250123:ios:c7a09c5814254aff1b45ce',
    messagingSenderId: '226229250123',
    projectId: 'tugasmandiri-jovan',
    databaseURL: 'https://tugasmandiri-jovan-default-rtdb.firebaseio.com',
    storageBucket: 'tugasmandiri-jovan.firebasestorage.app',
    iosBundleId: 'com.example.tugasIndividuFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVEtaTuxkPKzq9cql_jZSCfbD-AXj33yc',
    appId: '1:226229250123:ios:c7a09c5814254aff1b45ce',
    messagingSenderId: '226229250123',
    projectId: 'tugasmandiri-jovan',
    databaseURL: 'https://tugasmandiri-jovan-default-rtdb.firebaseio.com',
    storageBucket: 'tugasmandiri-jovan.firebasestorage.app',
    iosBundleId: 'com.example.tugasIndividuFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHSJ5NNXT665trCpLkAEGNalN8lkVLKnc',
    appId: '1:226229250123:web:a8067a9ddc0fde6e1b45ce',
    messagingSenderId: '226229250123',
    projectId: 'tugasmandiri-jovan',
    authDomain: 'tugasmandiri-jovan.firebaseapp.com',
    databaseURL: 'https://tugasmandiri-jovan-default-rtdb.firebaseio.com',
    storageBucket: 'tugasmandiri-jovan.firebasestorage.app',
    measurementId: 'G-6GPQJDYDJV',
  );
}
